CREATE TABLE meals
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255),
    weight        FLOAT,
    calories      FLOAT,
    fats          FLOAT,
    proteins      FLOAT,
    carbohydrates FLOAT,
    create_at     TIMESTAMP WITHOUT TIME ZONE,
    update_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_meals PRIMARY KEY (id)
);